[package]
name = "gsnag-overlay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gsnag-i18n.workspace = true
anyhow.workspace = true
gsnag-core.workspace = true
image.workspace = true
gtk4.workspace = true
gtk4-layer-shell.workspace = true
