[package]
name = "gsnag-record"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
gsnag-core.workspace = true
gsnag-proto.workspace = true
tempfile.workspace = true
ffmpeg-next = { version = "8", default-features = false, features = ["codec", "format", "software-scaling", "software-resampling"] }
pipewire = "0.9"
